### ISSUE TITLE
add a license

### ISSUE THREAD

**Issue by mattstratton** [DevOpsDaysChicago/dodchi-docs#1]

**Comment by kevinreedy** [comment]
Just went through something similar with another organization. We settled on Creative Commons Attribution-ShareAlike 4.0 International. https://creativecommons.org/choose/ is helpful for choosing types of Creative Commons licenses.

**Comment by mattstratton** [comment]
Fixed in 3e4c778dbb77c1e854c74779914192e1761699e8
